// 'use client';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConditionalLayout from "@/components/ConditionalLayout";
import Script from "next/script";
// import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export const metadata = {
  title: "Projet Moon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  // useEffect(() => {
  //   const AOS = require('aos');
  //   AOS.init({
  //     duration: 600,
  //     easing: 'ease-in-out',
  //     once: true,
  //   });
  // }, []);

  return (
    <html lang="fr" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        {/* Vendor CSS */}
        <link href="/vender/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <link href="/vender/icofont/icofont.min.css" rel="stylesheet" />
        <link href="/vender/aos/aos.css" rel="stylesheet" />
        <link href="/vender/remixicon/remixicon.css" rel="stylesheet" />

        {/* CSS personnalisé */}
        <link href="/css/style.css" rel="stylesheet" />
        <link href="/css/common.css" rel="stylesheet" />
      </head>
      <body data-aos-easing="ease" data-aos-duration="400" data-aos-delay="0">
        <ConditionalLayout>
          {children}
        </ConditionalLayout>

        {/* Scripts avec Next.js Script component */}
        <Script
          src="/vender/bootstrap/js/bootstrap.bundle.min.js"
          strategy="afterInteractive"
        />
        <Script
          src="/vender/jquery/jquery-3.6.4.min.js"
          strategy="afterInteractive"
        />
        <Script
          src="/vender/aos/dist/aos.js"
          strategy="afterInteractive"
        />
        <Script
          src="/js/script.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}