// 'use client';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConditionalLayout from "@/components/ConditionalLayout";
import Script from "next/script";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


export const metadata = {
  title: "Projet Moon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  // useEffect(() => {
  //   const AOS = require('aos');
  //   AOS.init({
  //     duration: 600,
  //     easing: 'ease-in-out',
  //     once: true,
  //   });
  // }, []);

  return (
    <html lang="fr">
      <head>
        {/* Vendor CSS */}
        <link href="/vender/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <link href="/vender/icofont/icofont.min.css" rel="stylesheet" />
        <link href="/vender/aos/aos.css" rel="stylesheet" />
        <link href="/vender/remixicon/remixicon.css" rel="stylesheet" />

        {/* CSS personnalisé */}
        <link href="/css/style.css" rel="stylesheet" />
        <link href="/css/common.css" rel="stylesheet" />

        <link
          href="https://fonts.cdnfonts.com/css/erotique-alternate-trial"
          rel="stylesheet"
        />

        <style>{`
          /* ===== Police Erotique pour les titres ===== */
          @font-face {
            font-family: 'Erotique';
            src: url('/fonts/Erotique/Erotique-Regular.ttf') format('truetype');
            font-weight: 400;
            font-style: normal;
          }
          @font-face {
            font-family: 'Erotique';
            src: url('/fonts/Erotique/Erotique-Bold.ttf') format('truetype');
            font-weight: 700;
            font-style: normal;
          }

          /* ===== Police Dosis pour le texte ===== */
          @font-face {
            font-family: 'Dosis';
            src: url('/fonts/Dosis/Dosis-Regular.ttf') format('truetype');
            font-weight: 400;
            font-style: normal;
          }
          @font-face {
            font-family: 'Dosis';
            src: url('/fonts/Dosis/Dosis-Bold.ttf') format('truetype');
            font-weight: 700;
            font-style: normal;
          }

          /* ===== Application des polices ===== */
          html, body {
            font-family: 'Dosis', sans-serif !important;
            font-weight: 400;
          }

          h1, h2, h3, h4, h5, h6 {
            font-family: 'Erotique', serif !important;
            
          }
        `}</style>
      </head>
      <body data-aos-easing="ease" data-aos-duration="400" data-aos-delay="0">
        <ConditionalLayout>
          {children}
        </ConditionalLayout>

        {/* Scripts avec Next.js Script component */}
        <Script
          src="/vender/bootstrap/js/bootstrap.bundle.min.js "
          async strategy="afterInteractive"
        />
        <Script
          src="/vender/jquery/jquery-3.6.4.min.js"
          strategy="afterInteractive"
        />
        <Script
          src="/vender/aos/dist/aos.js"
          strategy="afterInteractive"
        />
        <Script
          src="/js/script.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}